spring:
  profiles: docker

  datasource:
    url: jdbc:mysql://mysql-service:3306/authservice?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
