spring:
  application:
    name: notification-service
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:default@gmail.com}
    password: ${GMAIL_PASSWORD:defaultpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:default_account_sid}
  auth-token: ${TWILIO_AUTH_TOKEN:default_auth_token}
  phone-number: ${TWILIO_PHONE_NUMBER:+1234567890}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
